title: Sen Tech Blog
description: "Technology Blogs|Working Experiences Sharing"

name: Sen Liao
email: sen.liao@outlook.com

url: https://sen-ls.github.io        # e.g. https://sen-ls.github.io
baseurl: ""    # for project site: /repo-name

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - categories/routing.md
  - categories/switching.md
  - categories/storage.md
  - categories/virtual-computing.md
  - categories/projects.md
  - categories/wireless.md


minima:
  social_links:
    - platform: github
      user_url: https://github.com/sen-ls
    - platform: linkedin
      user_url: https://www.linkedin.com/in/sen-liao-737971164/

show_excerpts: true
timezone: Europe/Berlin
markdown: kramdown
